### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 4,
  "accountNumber": "0453080381",
  "amount": 100
}
### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 4,
  "accountNumber": "0453080381",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "21a30f4f60934f83be48831b146c7c7c",
  "accountNumber": "0453080381",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/4e38ecb720694ec981a9736bf6eb4ff0